CHECK_TARGETS += own-analyzer
FIX_TARGETS   += own-fixer
GROUP_TARGETS += own-group
TEST_TARGETS  += own-test

include ../../../../../conf/Makefile

#-- extras

#!! Makefile of a project that adds a fixer, an analyzer, a test and a grouping target of its own

own-analyzer: #~~ this project's own analyzer
	@printf 'own analyzer\n'

own-fixer: #~~ this project's own fixer
	@printf 'own fixer\n'

own-group: #~~ this project's own grouping target
	@printf 'own group\n'

own-test: #~~ this project's own test
	@printf 'own test\n'
