include ../../../../../conf/Makefile

#-- consumer

#!! Makefile of a project that includes the shared one

consumer-command: #~~ a target this project defines itself
	@echo consumer-command

consumer-arguments: #~~ prints the arguments this run handed it
	@echo "consumer-arguments [$(ARGS)] [$(ARG1)]"

consumer-arguments-second: #~~ prints the arguments a second target is handed
	@echo "consumer-arguments-second [$(ARGS)] [$(ARG1)]"
