include ../../../../../conf/Makefile

#-- suggestions

#!! Makefile of a project whose typos have both a target and a stage goal nearby

dumps: #~~ a target two edits from `de-ps`, which is one from `dev-ps`
	@echo dumps

ps: #~~ a target its stage goal `dev-ps` prefixes
	@echo ps
