include ../../../../../conf/Makefile

STARTUP_TARGETS := startup-own

#-- startup

#!! Makefile of a fresh checkout that has to be brought up

startup-own: #~~ the step this project adds to `startup`
	$(DEBUG_PREFIX)echo startup-own
